services:
  postgres:
    image: postgres:15-alpine
    container_name: quiz_postgres
    environment:
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: quiz_password
      POSTGRES_DB: quiz_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U quiz_user -d quiz_db' ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
